services:
  backend:
    build:
      args:
        - NODE_ENV=development
      context: backend
      target: development
    environment:
      - MYSQL_HOST=db
    ports:
      - 3000:3000
    volumes:
      - ./backend/src:/code/src:ro
      - ./backend/package.json:/code/package.json
      - ./backend/package-lock.json:/code/package-lock.json
    networks:
      - private
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/mysql/docker-data/mysqldata:/var/lib/mysql
      - ./docker/mysql/docker-data/dumps:/tmp/dump
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - private
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
       - "3306:3306"

networks:
  private:
